#!/usr/bin/env bash

##
# Install forge globally by creating a
# symlink in /usr/local/bin to globalize
# the forge cmd.
#
# Arguments:
#   None
#
# Returns:
#   None
##
install () {
    # create global cmd (symlink)
    DIR=${0%/*}
    if [[ "$DIR" == "." ]]; then
        DIR=$(pwd)
    fi
    ln -sf $DIR/forge /usr/local/bin/forge
}

install $@
