#!/usr/bin/env bash

#***********************************************#
#
# File:
#   install
#
# Purpose:
#   forge install executable. Will create a
#   symlink in /usr/local/bin to globalize
#   the forge cmd, and will prompt for a target
#   project and install the base forge tasks
#
#***********************************************#

install () {
    # create global cmd (symlink)
    DIR=${0%/*}
    if [[ "$DIR" == "." ]]; then
        DIR=$(pwd)
    fi
    ln -sf $DIR/forge /usr/local/bin/forge

    # grab where to install forge from the user
    read -p "Enter the target project root directory to install forge (i.e. $HOME/Development/project): " project_root

    # create .forge directory in project
    # and copy down base tasks
    if [[ -n $project_root ]]; then
        mkdir -p $project_root/.forge
        cp -Rn tasks $project_root/.forge/
    fi
}

install $@
