#!/usr/bin/env bash
run_task "sample-bash-task"
run_task "sample-node-task"
run_task "sample-python-task"
run_task "sample-ruby-task"

version_control "$PROJECT_ROOT/package.json" "npm install"
version_control "$PROJECT_ROOT/requirements.txt" "$PROJECT_ROOT/venv/bin/activate && pip install --disable-pip-version-check -r $PROJECT_ROOT/requirements.txt"
