#!/usr/bin/env ruby

=begin
    @forge
        Task:
            sample-ruby-task

        Purpose:
            Sample Ruby task

        Arguments:
            None
    @forge
=end

puts 'Hello Ruby'
